FILE_IS_GENERATED_COMMENT = """{{comment_tag}} This file has been generated by `{{file}}`
{{comment_tag}} file, placed in `{{path}}`
{{comment_tag}} -------------------------------------------------------------------

"""
